[package]

name = "dimensioned"
version = "0.0.2"
authors = ["Paho Lurie-Gregg <paho@paholg.com>"]
description = "A library for performing arthimetic with physical quantities with compile time type-checking."
repository = "https://github.com/paholg/dimensioned"
readme = "README.md"
license = "MIT"
