[package]

name = "dimensioned"
version = "0.3.1"
authors = ["Paho Lurie-Gregg <paho@paholg.com>"]
description = "Compile-time type checking of arbitrary unit systems."
homepage = "http://paholg.com/dimensioned"
documentation = "http://paholg.com/doc/dimensioned"
repository = "https://github.com/paholg/dimensioned"
readme = "README.md"
license = "MIT/Apache-2.0"

[lib]
name = "dimensioned"
# fixme: this is temporary; sqrt() doesn't work with it.
# plugin = true

[dependencies]
  num = "*"
